spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/bookstore-jpa
    password: '242824'
  application:
    name: jpa
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
    show:
      sql: 'true'
    hibernate:
      ddl-auto: update

